const CODE_SUCCESS = 200;
const CODE_CREATED = 201;
const CODE_INTERNAL_SERVER = 500;
const CODE_BAD_REQUEST = 400;

module.exports = {
  CODE_SUCCESS,
  CODE_CREATED,
  CODE_INTERNAL_SERVER,
  CODE_BAD_REQUEST
};
